name: todo_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  awesome_notifications_core: ^0.10.0
  awesome_notifications: ^0.10.1
  flutter:
    sdk: flutter
  flutter_timezone: ^4.1.1
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  sqlite3: ^2.9.0
  timezone: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
